# Generated by Django 2.2 on 2021-09-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0003_auto_20210826_2139'),
        ('better_self_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user_who_liked',
            field=models.ManyToManyField(related_name='quote_liker', to='login_registration_app.User'),
        ),
    ]
