# Generated by Django 2.2 on 2021-09-05 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0003_auto_20210826_2139'),
        ('better_self_app', '0002_quote_user_who_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.CharField(max_length=255)),
                ('measurement', models.CharField(max_length=255)),
                ('direction', models.IntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_user', to='login_registration_app.User')),
            ],
        ),
    ]
