# Generated by Django 2.2 on 2021-09-07 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0003_auto_20210826_2139'),
        ('better_self_app', '0004_baseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total', models.IntegerField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_program', to='better_self_app.Program')),
                ('user_intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_user', to='login_registration_app.User')),
            ],
        ),
    ]
