# Generated by Django 2.2 on 2021-10-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_self_app', '0005_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='goal',
            field=models.IntegerField(null=True),
        ),
    ]
