# Generated by Django 3.2.23 on 2023-12-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_self_app', '0006_program_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseline',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
