# Generated by Django 2.2 on 2021-09-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0003_auto_20210826_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
    ]
